"""add knowledge base and chat schema

Revision ID: 894de2b8cebd
Revises: 15264e15fc09
Create Date: 2026-08-14 15:59:07.335687

Adds the knowledge base (pgvector-backed) and chat schema: knowledge_entries,
conversations, messages, message_sources, feedback, website_analyses.

Autogenerate produced the table/index shape correctly but can't know about
three things, added by hand below: creating the `vector` extension (needed
before the `embedding` column's type can be used), explicitly creating the
5 new Postgres enum types before they're referenced in columns (same
pattern as the `app_role` enum in the baseline revision), and dropping
those enum types on downgrade (dropping the tables doesn't drop the types).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '894de2b8cebd'
down_revision: Union[str, Sequence[str], None] = '15264e15fc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("create extension if not exists vector")

    # create_type=False on each: these are constructed standalone (no
    # .metadata), so without this flag, the CREATE TABLE below would try to
    # auto-create the type a second time via the enum column's
    # before_create event and fail with "type already exists" -- the
    # explicit .create() call below is the only place each type gets
    # created.
    persona_enum = postgresql.ENUM(
        "sell_motm", "support_customer", name="persona", create_type=False
    )
    persona_enum.create(op.get_bind())
    knowledge_persona_enum = postgresql.ENUM(
        "sell_motm", "support_customer", "shared", name="knowledge_persona", create_type=False
    )
    knowledge_persona_enum.create(op.get_bind())
    knowledge_type_enum = postgresql.ENUM(
        "principle_card",
        "case_card",
        "objection",
        "positioning",
        "pricing",
        "other",
        name="knowledge_type",
        create_type=False,
    )
    knowledge_type_enum.create(op.get_bind())
    message_sender_enum = postgresql.ENUM(
        "user", "assistant", name="message_sender", create_type=False
    )
    message_sender_enum.create(op.get_bind())
    feedback_rating_enum = postgresql.ENUM(
        "useful", "not_useful", name="feedback_rating", create_type=False
    )
    feedback_rating_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('persona', persona_enum, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='conversations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('conversations_user_id_idx', 'conversations', ['user_id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona', knowledge_persona_enum, nullable=False),
    sa.Column('type', knowledge_type_enum, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], name='knowledge_entries_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('knowledge_entries_embedding_hnsw_idx', 'knowledge_entries', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('knowledge_entries_persona_idx', 'knowledge_entries', ['persona'], unique=False)
    op.create_index('knowledge_entries_type_idx', 'knowledge_entries', ['type'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender', message_sender_enum, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pipeline_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('messages_conversation_id_idx', 'messages', ['conversation_id'], unique=False)
    op.create_table('website_analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='website_analyses_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('website_analyses_conversation_id_idx', 'website_analyses', ['conversation_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', feedback_rating_enum, nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='feedback_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='feedback_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('feedback_message_id_idx', 'feedback', ['message_id'], unique=False)
    op.create_index('feedback_user_id_idx', 'feedback', ['user_id'], unique=False)
    op.create_table('message_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_entry_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_entry_id'], ['knowledge_entries.id'], name='message_sources_knowledge_entry_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='message_sources_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('message_sources_knowledge_entry_id_idx', 'message_sources', ['knowledge_entry_id'], unique=False)
    op.create_index('message_sources_message_id_idx', 'message_sources', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('message_sources_message_id_idx', table_name='message_sources')
    op.drop_index('message_sources_knowledge_entry_id_idx', table_name='message_sources')
    op.drop_table('message_sources')
    op.drop_index('feedback_user_id_idx', table_name='feedback')
    op.drop_index('feedback_message_id_idx', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('website_analyses_conversation_id_idx', table_name='website_analyses')
    op.drop_table('website_analyses')
    op.drop_index('messages_conversation_id_idx', table_name='messages')
    op.drop_table('messages')
    op.drop_index('knowledge_entries_type_idx', table_name='knowledge_entries')
    op.drop_index('knowledge_entries_persona_idx', table_name='knowledge_entries')
    op.drop_index('knowledge_entries_embedding_hnsw_idx', table_name='knowledge_entries', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_entries')
    op.drop_index('conversations_user_id_idx', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###

    # Types aren't dropped automatically when the tables using them are
    # dropped -- and the `vector` extension is intentionally left in place
    # (dropping extensions on downgrade is risky if anything else depends
    # on it).
    postgresql.ENUM(name="feedback_rating").drop(op.get_bind())
    postgresql.ENUM(name="message_sender").drop(op.get_bind())
    postgresql.ENUM(name="knowledge_type").drop(op.get_bind())
    postgresql.ENUM(name="knowledge_persona").drop(op.get_bind())
    postgresql.ENUM(name="persona").drop(op.get_bind())
