"""add llm call logs

Revision ID: b096cbd0b3e5
Revises: d4e5f6a7b8c9
Create Date: 2026-08-25 13:52:01.252601

Adds llm_call_logs, one row per individual LLM API call made anywhere in
the /chat pipeline (see app/services/usage_tracking.py and its callers in
app/services/llm.py / app/routers/chat.py), recording provider/model/token
counts/cost per call so spend can be broken down per pipeline step, not
just per user turn.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b096cbd0b3e5'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('call_name', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='llm_call_logs_conversation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='llm_call_logs_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='llm_call_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('llm_call_logs_conversation_id_idx', 'llm_call_logs', ['conversation_id'], unique=False)
    op.create_index('llm_call_logs_message_id_idx', 'llm_call_logs', ['message_id'], unique=False)
    op.create_index('llm_call_logs_user_id_idx', 'llm_call_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('llm_call_logs_user_id_idx', table_name='llm_call_logs')
    op.drop_index('llm_call_logs_message_id_idx', table_name='llm_call_logs')
    op.drop_index('llm_call_logs_conversation_id_idx', table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    # ### end Alembic commands ###
